# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, pyautogui, keyboard
from threading import Thread
from pynput import keyboard
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Spammer(object):
    def setupUi(self, Spammer):
        Spammer.setObjectName("Spammer")
        Spammer.setWindowModality(QtCore.Qt.NonModal)
        Spammer.setFixedWidth(519)
        Spammer.setFixedHeight(382)
        
        self.formLayoutWidget = QtWidgets.QWidget(Spammer)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 361))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        
        self.start_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.start_button.setObjectName("start_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.start_button)
        
        self.input_text = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.input_text.setObjectName("input_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_text)
        
        self.open_file = QtWidgets.QPushButton(self.formLayoutWidget)
        self.open_file.setObjectName("open_file")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.open_file)
        
        self.stop_button = QtWidgets.QPushButton(self.formLayoutWidget)
        self.stop_button.setObjectName("stop_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.stop_button)

        self.retranslateUi(Spammer)
        QtCore.QMetaObject.connectSlotsByName(Spammer)

        self.running = False
        self.open_file.clicked.connect(self.promptFileOpen)
        self.start_button.clicked.connect(self.start_spam)
        self.stop_button.clicked.connect(self.stop_spam)
        Thread(target=self.input).start()

    def promptFileOpen(self):
        dialog = QtWidgets.QFileDialog()
        dialog.setNameFilter("Text (*.txt)")

        if dialog.exec():
            file = open(dialog.selectedFiles()[0], "r")
            data = file.read()
            self.input_text.setPlainText(data)

    def spam_thread(self):
        text = self.input_text.toPlainText().replace(" ", "š")
        for sentence in text.split():
            if (self.running == False): break
            pyautogui.typewrite(sentence.replace("š", " "), interval=.015)
            pyautogui.press("enter")
    
        self.running = False                

    def start_spam(self):
        if (self.running): return
        self.running = True
        Thread(target=self.spam_thread).start()

    def stop_spam(self):
        if (not self.running): return
        self.running = False

    def pressed(self, key):
        if (key == keyboard.Key.f5):
            self.start_spam()
        elif (key == keyboard.Key.f6):
            self.stop_spam()

    def input(self):
        with keyboard.Listener(on_press=self.pressed) as listener:
            listener.join()
        
    def retranslateUi(self, Spammer):
        _translate = QtCore.QCoreApplication.translate
        Spammer.setWindowTitle(_translate("Spammer", "Script Spammer"))
        self.start_button.setText(_translate("Spammer", "Start [F5]"))
        self.open_file.setText(_translate("Spammer", "Open File"))
        self.stop_button.setText(_translate("Spammer", "Stop [F6]"))


def main():
    app = QtWidgets.QApplication(sys.argv)
    Spammer = QtWidgets.QWidget()
    ui = Ui_Spammer()
    ui.setupUi(Spammer)
    Spammer.show()
    sys.exit(app.exec_())

main()
